#!/usr/bin/env sh

# Usage
#   $ gist <filepath> <description>

filepath=${1:?}
description=${2:?}

filename=$(basename $filepath)
extension=txt # XXX: unused!?

user=`head -n1 ~/.githubconfig`
token=`tail -n1 ~/.githubconfig`

url="https://gist.github.com/gists"
pattern="< Location: https:\/\/gist.github.com\/"

id=$(curl --verbose \
	--request POST \
	--data "login=$user&token=$token" \
	--data "file_ext[gistfile1]=$extension&file_name[gistfile1]=$filename" \
	--data "file_contents[gistfile1]=$description" \
	$url 2>&1 | \
	grep "$pattern" | sed -e "s/$pattern//" -e "s/\r//")
	#--data action_button=private # XXX: unused

url="https://gist.github.com/$id"
echo "created $url; cloning repository"

sleep 2
uri="git@gist.github.com:$id.git"
path="gist_$id"
git clone $uri $path || \
	echo "could not clone Gist repository: $uri"

cd $path && rm $filename && ln ../$filename && \
	git commit -a -m "initial commit" && \
	git push && \
echo "cloned $url in directory $path"
